export * from './auth/auth.component';
export * from './auth/login/login.component';
export * from './auth/register/register.component';
export * from './battle-details/battle-details.component';
export * from './battles/battles.component';
export * from './dashboard/dashboard.component';
export * from './home/home.component';
export * from './settings/settings.component';
export * from './spec-details/spec-details.component';
